name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: action/checkout@4
      - uses: action/setup-node@4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check Style
        run: npm run eslint
